// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, log, port;

  express = require('express');

  log = require('glogger')('GUYHT');

  port = process.env.VCAP_APP_PORT || 3000;

  log.info("Starting server on port " + port);

  app = express().use(express.logger({
    format: 'tiny',
    stream: log.stream()
  })).use(express.compress()).use(express.responseTime()).use(express["static"]('publish'));

  app.get('/blog*', function(req, res) {
    var url;
    url = req.url;
    log.info("Redirecting blog request for " + url);
    url = url.replace('/blog', '');
    return res.redirect("http://blog.guy.ht" + url, 301);
  });

  app.listen(port);

}).call(this);
